### PR TITLE
[Fix]: Responsive Header

### PR DESCRIPTION
**Pull request by Petsamuel**
test link: https://yyxdkq-5173.csb.app/ #12

### CODE REVIEW

**Comment by hossainchisty** [comment]
Hi, @Petsamuel We need to change button size and search bar size its so large! and don't change the color of button

image

**Comment by hossainchisty** [comment]
We won't be changing this style for now; we intend to stick with it. We just need to create a responsive header for mobile screens. We hope you understand!

image

**Comment by Petsamuel** [comment]
@hossainchisty kindly confirm if this better via:https://yyxdkq-5173.csb.app/

**Comment by hossainchisty** [comment]
### Mobile Screen View
- We are unable to type in the search bar. Additionally, the hamburger menu is unresponsive on small devices and does not display any content.

**Anonymous User**
image

**Logged User**
image

**Comment by Petsamuel** [comment]
@hossainchisty kindly confirm

**Comment by hossainchisty** [comment]
🚀 Thanks @Petsamuel! Your contribution is a huge help to the project. I appreciate your support and the time you've invested. Keep up the good work!

**Pull request merged**
